/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        patch: operations["update_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_expenses_api_v1_expenses_get"];
        put?: never;
        post: operations["create_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_expense_api_v1_expenses__expense_id__delete"];
        options?: never;
        head?: never;
        patch: operations["update_expense_api_v1_expenses__expense_id__patch"];
        trace?: never;
    };
    "/api/v1/incomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_incomes_api_v1_incomes_get"];
        put?: never;
        post: operations["create_income_api_v1_incomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incomes/{income_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_income_api_v1_incomes__income_id__delete"];
        options?: never;
        head?: never;
        patch: operations["update_income_api_v1_incomes__income_id__patch"];
        trace?: never;
    };
    "/api/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monthly_report_api_v1_reports_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_recurrences_api_v1_recurrences_get"];
        put?: never;
        post: operations["create_recurrence_api_v1_recurrences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurrences/{recurrence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_recurrence_api_v1_recurrences__recurrence_id__delete"];
        options?: never;
        head?: never;
        patch: operations["update_recurrence_api_v1_recurrences__recurrence_id__patch"];
        trace?: never;
    };
    "/api/v1/recurrences/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run_recurrences_api_v1_recurrences_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export_backup_api_v1_backup_get"];
        put?: never;
        post: operations["import_backup_api_v1_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_profile_api_v1_profile_get"];
        put: operations["update_profile_api_v1_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProfileGoal: {
            name: string;
            target_amount?: number | null;
            /** @example 2027-06 */
            target_date?: string | null;
        };
        UpdateProfileRequest: {
            alias?: string | null;
            birth_year?: number | null;
            city?: string | null;
            /** @example CO */
            country_code?: string | null;
            estimated_monthly_income?: number | null;
            estimated_monthly_expenses?: number | null;
            /** @enum {string|null} */
            income_type?: "fixed" | "variable" | "mixed" | null;
            dependents_count?: number | null;
            /** @enum {string|null} */
            housing?: "rent" | "owned" | "family" | null;
            /** @enum {string|null} */
            risk_tolerance?: "low" | "medium" | "high" | null;
            concerns?: string[] | null;
            goals?: components["schemas"]["ProfileGoal"][] | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        ProfileResponse: {
            alias: string | null;
            birth_year: number | null;
            city: string | null;
            country_code: string | null;
            estimated_monthly_income: number | null;
            estimated_monthly_expenses: number | null;
            /** @enum {string|null} */
            income_type: "fixed" | "variable" | "mixed" | null;
            dependents_count: number | null;
            /** @enum {string|null} */
            housing: "rent" | "owned" | "family" | null;
            /** @enum {string|null} */
            risk_tolerance: "low" | "medium" | "high" | null;
            concerns: string[];
            goals: components["schemas"]["ProfileGoal"][];
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CategoryResponse: {
            id: number;
            name: string;
            icon: string | null;
            sort_order: number;
            /** @enum {string} */
            kind: "expense" | "income";
            is_system: boolean;
            is_active: boolean;
        };
        CreateCategoryRequest: {
            name: string;
            /** @enum {string} */
            kind: "expense" | "income";
            icon: string | null;
        };
        UpdateCategoryRequest: {
            name?: string | null;
            icon?: string | null;
            is_active?: boolean | null;
        };
        CreateExpenseRequest: {
            amount_cents: number;
            currency: string;
            category_id: number;
            /** Format: date */
            occurred_on: string;
            note?: string | null;
        };
        UpdateExpenseRequest: {
            amount_cents?: number | null;
            currency?: string | null;
            category_id?: number | null;
            /** Format: date */
            occurred_on?: string | null;
            note?: string | null;
            recurrence_id?: number | null;
        };
        ExpenseResponse: components["schemas"]["CreateExpenseRequest"] & {
            id: number;
            recurrence_id: number | null;
        };
        ExpensePageResponse: {
            items: components["schemas"]["ExpenseResponse"][];
            total: number;
        };
        CreateIncomeRequest: {
            amount_cents: number;
            currency: string;
            source_id: number;
            /** Format: date */
            occurred_on: string;
            note?: string | null;
        };
        UpdateIncomeRequest: {
            amount_cents?: number | null;
            currency?: string | null;
            source_id?: number | null;
            /** Format: date */
            occurred_on?: string | null;
            note?: string | null;
            recurrence_id?: number | null;
        };
        IncomeResponse: components["schemas"]["CreateIncomeRequest"] & {
            id: number;
            recurrence_id: number | null;
        };
        IncomePageResponse: {
            items: components["schemas"]["IncomeResponse"][];
            total: number;
        };
        CategoryBreakdownResponse: {
            category_id: number;
            category_name: string;
            category_icon: string | null;
            total_cents: number;
        };
        SourceBreakdownResponse: {
            source_id: number;
            source_name: string;
            source_icon: string | null;
            total_cents: number;
        };
        MonthlyReportResponse: {
            year: number;
            month: number;
            expense_total_cents: number;
            previous_month_expense_total_cents: number;
            income_total_cents: number;
            previous_month_income_total_cents: number;
            net_cents: number;
            by_category: components["schemas"]["CategoryBreakdownResponse"][];
            by_source: components["schemas"]["SourceBreakdownResponse"][];
        };
        CreateRecurrenceRequest: {
            /** @enum {string} */
            kind: "expense" | "income";
            amount_cents: number;
            currency: string;
            category_id: number;
            /** @enum {string} */
            frequency: "monthly" | "biweekly";
            day_of_month: number;
            second_day_of_month?: number | null;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            note?: string | null;
        };
        UpdateRecurrenceRequest: {
            amount_cents?: number | null;
            currency?: string | null;
            category_id?: number | null;
            /** @enum {string|null} */
            frequency?: "monthly" | "biweekly" | null;
            day_of_month?: number | null;
            second_day_of_month?: number | null;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            note?: string | null;
            is_active?: boolean | null;
        };
        RecurrenceResponse: components["schemas"]["CreateRecurrenceRequest"] & {
            id: number;
            is_active: boolean;
            /** Format: date */
            next_occurrence_on: string | null;
        };
        BackupDocument: {
            expenses: components["schemas"]["CreateExpenseRequest"][];
            incomes?: components["schemas"]["CreateIncomeRequest"][];
        };
    };
    responses: {
        /** @description Successful Response */
        Category: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CategoryResponse"];
            };
        };
        /** @description Successful Response */
        Expense: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ExpenseResponse"];
            };
        };
        /** @description Successful Response */
        ExpensePage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ExpensePageResponse"];
            };
        };
        /** @description Successful Response */
        Income: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["IncomeResponse"];
            };
        };
        /** @description Successful Response */
        IncomePage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["IncomePageResponse"];
            };
        };
        /** @description Successful Response */
        Backup: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackupDocument"];
            };
        };
    };
    parameters: {
        Month: string;
        Limit: number;
        Offset: number;
        ExpenseID: number;
        IncomeID: number;
        CategoryID: number;
    };
    requestBodies: {
        CreateCategory: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        UpdateCategory: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        CreateExpense: {
            content: {
                "application/json": components["schemas"]["CreateExpenseRequest"];
            };
        };
        UpdateExpense: {
            content: {
                "application/json": components["schemas"]["UpdateExpenseRequest"];
            };
        };
        CreateIncome: {
            content: {
                "application/json": components["schemas"]["CreateIncomeRequest"];
            };
        };
        UpdateIncome: {
            content: {
                "application/json": components["schemas"]["UpdateIncomeRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: {
                kind?: "expense" | "income";
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["CreateCategory"];
        responses: {
            201: components["responses"]["Category"];
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: components["parameters"]["CategoryID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: components["parameters"]["CategoryID"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["UpdateCategory"];
        responses: {
            200: components["responses"]["Category"];
        };
    };
    list_expenses_api_v1_expenses_get: {
        parameters: {
            query: {
                month: components["parameters"]["Month"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ExpensePage"];
        };
    };
    create_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["CreateExpense"];
        responses: {
            201: components["responses"]["Expense"];
        };
    };
    delete_expense_api_v1_expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: components["parameters"]["ExpenseID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_expense_api_v1_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: components["parameters"]["ExpenseID"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["UpdateExpense"];
        responses: {
            200: components["responses"]["Expense"];
        };
    };
    list_incomes_api_v1_incomes_get: {
        parameters: {
            query: {
                month: components["parameters"]["Month"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["IncomePage"];
        };
    };
    create_income_api_v1_incomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["CreateIncome"];
        responses: {
            201: components["responses"]["Income"];
        };
    };
    delete_income_api_v1_incomes__income_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                income_id: components["parameters"]["IncomeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_income_api_v1_incomes__income_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                income_id: components["parameters"]["IncomeID"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["UpdateIncome"];
        responses: {
            200: components["responses"]["Income"];
        };
    };
    monthly_report_api_v1_reports_monthly_get: {
        parameters: {
            query: {
                month: components["parameters"]["Month"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportResponse"];
                };
            };
        };
    };
    list_recurrences_api_v1_recurrences_get: {
        parameters: {
            query?: {
                kind?: "expense" | "income" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurrenceResponse"][];
                };
            };
        };
    };
    create_recurrence_api_v1_recurrences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateRecurrenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurrenceResponse"];
                };
            };
        };
    };
    delete_recurrence_api_v1_recurrences__recurrence_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurrence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_recurrence_api_v1_recurrences__recurrence_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurrence_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateRecurrenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurrenceResponse"];
                };
            };
        };
    };
    run_recurrences_api_v1_recurrences_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    export_backup_api_v1_backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Backup"];
        };
    };
    import_backup_api_v1_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BackupDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    update_profile_api_v1_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
}
